# version: '3.8'

services:
  # -----------------------------
  # Base de données (PostgreSQL)
  # -----------------------------
  postgres:
    image: postgres:15
    container_name: ft_transcendence_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  # -----------------------------
  # Cache & Temps réel (Redis)
  # -----------------------------
  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    container_name: ft_transcendence_redis
    restart: always
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "6380:6379"
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]

  # -----------------------------
  # Backend (NestJS)
  # -----------------------------
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ft_transcendence_backend
    environment:
      POSTGRES_URL: ${POSTGRES_URL}
      REDIS_URL: ${REDIS_URL}
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres
      - redis
    # Command pour le dev (hot reload)
    command: npm run start:dev

  # -----------------------------
  # Frontend (React + Vite)
  # -----------------------------
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ft_transcendence_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    # Vite nécessite d'exposer l'hôte pour Docker
    command: npm run dev -- --host

# volumes:
#   ./data:/var/lib/postgresql/data
